# Generated by Django 3.2.1 on 2021-05-08 00:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='accounts.user')),
                ('gender', models.IntegerField(blank=True, choices=[(1, 'Female'), (2, 'Male'), (3, 'Non-binary'), (4, 'Decline to state')], default=4)),
                ('location', models.CharField(blank=True, max_length=100, null=True)),
                ('website', models.CharField(blank=True, max_length=100, null=True)),
                ('company', models.CharField(blank=True, max_length=100, null=True)),
                ('about_me', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
